// src/lib/components/welcome/start.svelte
<script lang="ts">
	import * as ionicons from 'ionicons/icons';
	import { navController } from 'ionic-svelte';
	import SignIn from '$lib/components/welcome/signin.svelte';
</script>

<ion-content fullscreen scroll-y={false} class="ion-padding">
	<ion-card>
		<ion-card-header>
			<ion-card-title>Welcome to Stolas!</ion-card-title>
			<ion-card-subtitle>A Mobile-First Matrix Client</ion-card-subtitle>
		</ion-card-header>
		<ion-card-content>
			<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
			<ion-button
				expand="block"
				on:click={() => {
					navController.push(SignIn, {});
				}}
			>
				<ion-icon slot="start" icon={ionicons.logIn} aria-hidden="true" />
				Sign in
			</ion-button>
			<ion-button expand="block" color="secondary">
				<ion-icon slot="start" icon={ionicons.add} aria-hidden="true" />
				Create account
			</ion-button>
		</ion-card-content>
	</ion-card>
</ion-content>

// src/pages/welcome/Start.tsx
import {
	IonButton,
	IonCard,
	IonCardContent,
	IonCardHeader,
	IonCardSubtitle,
	IonCardTitle,
	IonContent,
	IonIcon,
	IonPage
} from '@ionic/react';
import { logIn, add } from 'ionicons/icons';
import { useTranslation } from 'react-i18next';
import { useTitle } from '../../lib/title';
import React from 'react';

const Start: React.FC = () => {
	const { t } = useTranslation();
	useTitle(t('welcome.start.page.title'));
	return (
		<IonPage>
			<IonContent fullscreen class="ion-padding">
				<IonCard>
					<IonCardHeader>
						<IonCardTitle>{t('welcome.start.title')}</IonCardTitle>
						<IonCardSubtitle>{t('welcome.start.subtitle')}</IonCardSubtitle>
					</IonCardHeader>
					<IonCardContent>
						<IonButton expand="block" routerLink="/welcome/sign-in">
							<IonIcon icon={logIn} slot="start" />
							{t('welcome.start.sign_in')}
						</IonButton>
						<IonButton expand="block" color="secondary">
							<IonIcon icon={add} slot="start" />
							{t('welcome.start.create_account')}
						</IonButton>
					</IonCardContent>
				</IonCard>
			</IonContent>
		</IonPage>
	);
};
export default Start;
